### ISSUE TITLE
'https://appregistry-posteid.mobile.poste.it/jod-app-registry/v2/register' responds 403 Forbidden

### ISSUE THREAD

**Issue by ilmanowar** [simone36050/PosteID-seed-extractor#1]
Not sure about the language for writing the issue. 

As in the title the page responds with a 403 error.
This is the output of the script:

`python3.7 extractor.py extract`
`Traceback (most recent call last):`
 ` File "extractor.py", line 482, in <module>`
 `   main()`
 ` File "extractor.py", line 474, in main`
 `   extract_cmd(args.only_output, args.show_string)`
 ` File "extractor.py", line 378, in extract_cmd`
 `   app_privkey, server_key)`
 ` File "extractor.py", line 63, in http_registration`
 `   assert r.status_code == 200, 'Registration failed ({} != 200)'.format(r.status_code)`
`AssertionError: Registration failed (403 != 200)`

**Comment by simone36050** [comment]
Hi. Thanks for the report.

The error is probably due to a temporary problem with PosteID servers, I just tried it and it works for me, I suggest you try again and post here if it worked.

**Comment by simone36050** [comment]
Since this thread is inactive, I am closing it.
